### ISSUE TITLE
RTL problem

### ISSUE THREAD

**Issue by Mahmoudgomaa001** [yshalsager/ebook-converter-bot#75]
Can you add to css file : 

html *
{
 text-align: right !important;
  direction: rtl !important;
}

adding rtl to doc is not enough.

**Comment by Mahmoudgomaa001** [comment]
Thank you for the modifications you made, but there is a problem with some books, the paragraphs are formatted to appear in the middle, and this is not good for e-readers.
Preferably, the direction of writing should be to the right.

**Comment by yshalsager** [comment]
> Thank you for the modifications you made, but there is a problem with some books, the paragraphs are formatted to appear in the middle, and this is not good for e-readers. Preferably, the direction of writing should be to the right.

You're welcome. I think it's better to keep the original formatting of the book.

**Comment by Mahmoudgomaa001** [comment]
Can u add it as additional option or something like that

**Comment by Mahmoudgomaa001** [comment]
Can u add it as an additional option or something like that
